apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensesweb
spec:
  selector:
    matchLabels:
      app: expensesweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: expensesweb
    spec:
      containers:
      - image: kamerer/php-apache
        name: expensesweb
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: expenses-web-storage
          mountPath: /var/www/html
      volumes:
      - name: expenses-web-storage
        persistentVolumeClaim:
          claimName: expenses-web-claim
---
apiVersion: v1
kind: Service
metadata:
  name: expensesweb
spec:
  type: NodePort  
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: expensesweb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: expenses-web-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/expenses"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expenses-web-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
